### ISSUE TITLE
password exposed

### ISSUE THREAD

**Issue by sformel-usgs** [idiv-biodiversity/effects_of_automated_cleaning#1]
@azizka I ended up in this repo because I really enjoyed the associated paper. Thanks for the excellent work!

I noticed that your GBIF password is exposed in the script https://github.com/idiv-biodiversity/effects_of_automated_cleaning/blob/master/01_download_data_from_gbif.R

I just checked and it is still valid and allows me to login to GBIF as you.  An alternative is to use `rstudioapi::askForPassword()` to avoid hardcoding the password.

**Comment by azizka** [comment]
Good catch, thanks! Glad that you liked the paper.
